### ISSUE TITLE
Denon AVR-X3500H not fully supported

### ISSUE THREAD

**Issue by davidsuarez82** [ol-iver/denonavr#177] opened 2020-12-28 13:29 UTC
Hi I'm getting the following errors in the Home Assistant log

Updating denonavr media_player took longer than the scheduled update interval 0:00:10
Source: helpers/entity_platform.py:603

Update of media_player.denon_avr is taking over 10 seconds
Source: helpers/entity.py:477

Host 192.168.70.29 returned HTTP status code 403 to POST command at end point /goform/AppCommand.xml
Source: /usr/local/lib/python3.8/site-packages/denonavr/denonavr.py:447

Getting renamed and deleted sources failed.
Source: /usr/local/lib/python3.8/site-packages/denonavr/denonavr.py:1088

Host 192.168.70.29 returned HTTP status code 403 to GET request at end point /goform/formMainZone_MainZoneXml.xml
Host 192.168.70.29 returned HTTP status code 403 to GET request at end point /goform/formMainZone_MainZoneXmlStatus.xml
Source: /usr/local/lib/python3.8/site-packages/denonavr/denonavr.py:415

Missing status information from XML of Main for: Power, InputFuncSelect, Mute, MasterVolume
Source: /usr/local/lib/python3.8/site-packages/denonavr/denonavr.py:599

Can I help you to have this device fully implemented?

**Comment by JPHutchins** [comment] 2020-12-28 17:52
Duplicate of https://github.com/scarface-4711/denonavr/issues/166, fix is incoming.  Also see here: https://github.com/home-assistant/core/issues/43670

**Comment by davidsuarez82** [comment] 2020-12-28 18:26
I missed those; thanks :)

**Closed as completed** 2020-12-28 18:26 UTC
